[AbilityToSlotReassignment.AbilityToSlotReassignmentLib]

; Required because Musashi's Mods Fixes autoconfigures AdditionalAbilities
+AbilityWeaponCategories = (AbilityName = "F_CoordinateFire_Attack", WeaponCategorySetName = "AllMainWeaponsPlusPistols")
+AbilityWeaponCategories = (AbilityName = "F_CoordinateFire_Attack", WeaponCategorySetName = "ChemthrowerPlusSparkRifle")

+AbilityWeaponCategories = (AbilityName = "F_LikeLightning", WeaponCategorySetName = "ArcthrowerOnly")
+AbilityWeaponCategories = (AbilityName = "F_LikeLightning_Refund", WeaponCategorySetName = "ArcthrowerOnly")
+AbilityWeaponCategories = (AbilityName = "F_PerfectGuard", WeaponCategorySetName = "ShieldsOnly")
+AbilityWeaponCategories = (AbilityName = "F_ShieldTrauma", WeaponCategorySetName = "ShieldsOnly")
+AbilityWeaponCategories = (AbilityName = "F_ProtectAndServe", WeaponCategorySetName = "ShieldsOnly")
+AbilityWeaponCategories = (AbilityName = "F_FaultlessDefense", WeaponCategorySetName = "ShieldsOnly")
+AbilityWeaponCategories = (AbilityName = "F_BolsteredWall", WeaponCategorySetName = "ShieldsOnly")
+AbilityWeaponCategories = (AbilityName = "F_ShoulderToLeanOn", WeaponCategorySetName = "ShieldsOnly")
+AbilityWeaponCategories = (AbilityName = "F_ShoulderToLeanOn_Passive", WeaponCategorySetName = "ShieldsOnly")
+AbilityWeaponCategories = (AbilityName = "F_StayCovered", WeaponCategorySetName = "ShieldsOnly")
+AbilityWeaponCategories = (AbilityName = "F_Safeguard", WeaponCategorySetName = "ShieldsOnly")
+AbilityWeaponCategories = (AbilityName = "F_Safeguard_Passive", WeaponCategorySetName = "ShieldsOnly")
+AbilityWeaponCategories = (AbilityName = "F_Guard", WeaponCategorySetName = "ShieldsOnly")
+AbilityWeaponCategories = (AbilityName = "F_Guard_Activate", WeaponCategorySetName = "ShieldsOnly")
+AbilityWeaponCategories = (AbilityName = "F_PackTactics", WeaponCategorySetName = "ShieldsOnly")
+AbilityWeaponCategories = (AbilityName = "F_Parry", WeaponCategorySetName = "ShieldsOnly")
+AbilityWeaponCategories = (AbilityName = "F_Parry_Attack", WeaponCategorySetName = "ShieldsOnly")
+AbilityWeaponCategories = (AbilityName = "F_Parry_Preparation", WeaponCategorySetName = "ShieldsOnly")
+AbilityWeaponCategories = (AbilityName = "F_Parry_Counterattack", WeaponCategorySetName = "ShieldsOnly")
+AbilityWeaponCategories = (AbilityName = "F_Resupply", WeaponCategorySetName = "GremlinLike")
+AbilityWeaponCategories = (AbilityName = "F_Immunize", WeaponCategorySetName = "GremlinLike")
+AbilityWeaponCategories = (AbilityName = "F_Finesse", WeaponCategorySetName = "Melee")
+AbilityWeaponCategories = (AbilityName = "F_Rush", WeaponCategorySetName = "Melee")